import { config } from '../config/env.js'
import { Account } from '../models/Account.js'
import { createHttpError } from '../utils/httpError.js'
import { seedAccountForUser } from './accountController.js'
import { verifyToken } from '../utils/auth.js'

function getBearerToken(req) {
  const header = req.headers.authorization || ''
  const [scheme, token] = header.split(' ')

  if (scheme !== 'Bearer' || !token) {
    return null
  }

  return token
}

function getOptionalAuthPayload(req) {
  const token = getBearerToken(req)
  if (!token) return null

  return verifyToken(token, config.jwtSecret)
}

function normalizeItems(items = []) {
  if (!Array.isArray(items)) return []

  return items
    .map((item) => ({
      name: String(item?.name || item?.title || 'Item').trim(),
      quantity: Number(item?.quantity || item?.qty || 1) || 1,
      price: Number(item?.price || item?.subtotal || 0) || 0,
    }))
    .filter((item) => item.name)
}

async function verifyWithPaystack(reference) {
  // ── Mock / development mode ─────────────────────────────────────────────
  // If no secret key is configured and the reference is a local mock
  // reference (generated by the dev-mode Paystack simulation modal),
  // return a synthetic success payload so the full checkout flow can be
  // tested without real Paystack credentials.
  if (!config.paystack.secretKey && String(reference).startsWith('GR-MOCK-')) {
    return {
      status: 'success',
      amount: 0,          // amount is read from the cart on the client; 0 is fine for mock
      currency: 'NGN',
      reference,
      paid_at: new Date().toISOString(),
      customer: { email: '' },
    }
  }

  if (!config.paystack.secretKey) {
    throw createHttpError(500, 'Paystack secret key is not configured')
  }

  const response = await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`, {
    headers: {
      Authorization: `Bearer ${config.paystack.secretKey}`,
      Accept: 'application/json',
    },
  })

  const payload = await response.json().catch(() => null)
  if (!response.ok || !payload?.status) {
    throw createHttpError(502, payload?.message || 'Unable to verify payment with Paystack')
  }

  return payload.data
}

export async function verifyPaystackPayment(req, res, next) {
  try {
    const reference = String(req.body?.reference || req.query?.reference || '').trim()
    const items = normalizeItems(req.body?.items || [])
    const fallbackEmail = String(req.body?.email || '').trim()

    if (!reference) {
      return next(createHttpError(400, 'Payment reference is required'))
    }

    const verification = await verifyWithPaystack(reference)

    if (String(verification.status || '').toLowerCase() !== 'success') {
      return next(createHttpError(400, 'Payment was not successful'))
    }

    const amount = Number(verification.amount || 0) / 100
    const currency = String(verification.currency || 'NGN').toUpperCase()
    const customerEmail = String(verification.customer?.email || fallbackEmail || '').trim()
    const authPayload = getOptionalAuthPayload(req)

    let order = null
    if (authPayload?.sub) {
      const account = await seedAccountForUser(authPayload.sub)
      order = {
        orderNumber: account.orders.length + 1,
        product: items.length ? items.map((item) => item.name).join(', ') : 'Cart checkout',
        date: new Date(),
        status: 'Paid',
        total: amount,
        paymentReference: reference,
        paymentGateway: 'Paystack',
        currency,
        customerEmail,
        paidAt: new Date(verification.paid_at || Date.now()),
        items,
      }

      account.orders.push(order)
      await account.save()
    }

    res.json({
      ok: true,
      data: {
        reference,
        amount,
        currency,
        email: customerEmail,
        status: verification.status,
        gateway: 'Paystack',
        order,
      },
    })
  } catch (error) {
    next(error)
  }
}
